# Generated by Django 5.1.3 on 2024-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
