# Generated by Django 5.1.3 on 2024-12-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
